"use client";
import Head from "next/head";
import Link from "next/link";
import { useState } from "react";

export default function Counter() {
  const [count, setCount] = useState(0);
  return (
    <>
      <Head>
        <title>Skibidi</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <div>
          <button className="" onClick={() => {
            void setCount(count + 1);
          }}>
            <p className="text-sm font-bold text-[#B7B7B7]">RSVP:</p>
          </button>
          
          {count}
        </div>
      </main>
    </>
  );
}
